version: 2.1
executors:
  worker:
    docker:
      - image: fr3akyphantom/droid-builder:latest
jobs:
  build:
    executor: worker
    steps:
      - run:
          name: SSH
          command: |
            sudo apt update && sudo apt install git aria2 rsync neofetch nano tmux screen xclip silversearch* -y
            wget https://raw.githubusercontent.com/ibraaltabian17/Aosp-Builder/circleci-project-setup/envsetup.sh && sh envsetup.sh
            wget https://raw.githubusercontent.com/ibraaltabian17/Aosp-Builder/circleci-project-setup/envsetup.sh && sh mulairepo.sh
